services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ice-cream-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ice_cream_recipes;Username=icecream;Password=icecream_pass
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    depends_on:
      - postgres
      - seq
    networks:
      - ice-cream-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: icecream
      POSTGRES_PASSWORD: icecream_pass
      POSTGRES_DB: ice_cream_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/Database/InitialSchema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ice-cream-network

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - ice-cream-network

networks:
  ice-cream-network:
    driver: bridge

volumes:
  postgres_data:
  seq_data: