services:
  postgres:
    image: postgres:15
    container_name: ice-cream-recipes-db
    environment:
      POSTGRES_USER: icecream
      POSTGRES_PASSWORD: icecream_pass
      POSTGRES_DB: ice_cream_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./InitialSchema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    
  seq:
    image: datalust/seq:latest
    container_name: ice-cream-recipes-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  seq_data:
